image: docker:20.10.16
variables:
  GIT_DEPTH: '0' 

stages:
  - api-build
  - api-test
  - api-release
  - api-deploy

workflow:
    rules:
      - if: $CI_COMMIT_REF_NAME ==  "development"
        variables:
          DOCKER_TLS_CERTDIR: ""
          SERVER_IP: 203.109.103.26
          SERVER_USER: administrator
          DEPLOY_USER: epiu
          DEPLOY_PASSWORD: "Ethics@2023"
          CONTAINER_REGISTRY: https://index.docker.io/v1/
          CONTAINER_IMAGE: epiu/gtpos-api
          CONTAINER_TEST_IMAGE: $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG
          CONTAINER_RELEASE_IMAGE: $CONTAINER_IMAGE:dev
          CONTAINER_NAME: gtpos_api_dev
      

      - if: $CI_COMMIT_REF_NAME ==  "main"
        variables:
          DOCKER_TLS_CERTDIR: ""
          #SERVER_IP: 203.109.103.26
          #SERVER_USER: administrator
          DEPLOY_USER: epiu
          DEPLOY_PASSWORD: "Ethics@2023"
          CONTAINER_REGISTRY: https://index.docker.io/v1/
          CONTAINER_IMAGE: epiu/gtpos-api
          CONTAINER_TEST_IMAGE: $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG
          CONTAINER_RELEASE_IMAGE: $CONTAINER_IMAGE:qa
          CONTAINER_NAME: gtpos_api_stage
          #Determine whether batch is active or not by using these variables
          SALES_RETURN_BATCH_NO_FIELD_ID: field_1718275647729

      - if: $CI_COMMIT_REF_NAME ==  "production"
        variables:
          DOCKER_TLS_CERTDIR: ""
          #SERVER_IP: 203.109.103.26
          #SERVER_USER: administrator
          DEPLOY_USER: epiu
          DEPLOY_PASSWORD: "Ethics@2023"
          CONTAINER_REGISTRY: https://index.docker.io/v1/
          CONTAINER_IMAGE: epiu/gtpos-api
          CONTAINER_TEST_IMAGE: $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG
          CONTAINER_RELEASE_IMAGE: $CONTAINER_IMAGE:prod
          CONTAINER_NAME: gtpos_api
     

build:
  stage: api-build
  before_script:
    - docker login -u $DEPLOY_USER -p $DEPLOY_PASSWORD $CONTAINER_REGISTRY
  script:
    - cd server/express-api
    - docker build --pull -t $CONTAINER_TEST_IMAGE -f Dockerfile .
  rules:
    - if: $CI_COMMIT_REF_NAME ==  "main"


release:
  stage: api-release
  before_script:
    - docker login -u $DEPLOY_USER -p $DEPLOY_PASSWORD $CONTAINER_REGISTRY 
  script:
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  rules:
    - if: $CI_COMMIT_REF_NAME ==  "main"

deploy:
  stage: api-deploy
  script:
    - apk add --update curl
    - curl -XPOST $CD_URL_STAGE
  environment:
      name: stage-api
      url: http://apiqa.gtpos.ethicstechnology.net/
  rules:
    - if: $CI_COMMIT_REF_NAME ==  "main"

  
  