image: docker:20.10.16
variables:
  GIT_DEPTH: '0'
  
stages:
  - ui-build
  - ui-release
  - ui-deploy
 
workflow:
    rules:
      - if: $CI_COMMIT_REF_NAME ==  "development"
        variables:
          DOCKER_TLS_CERTDIR: ""
          #SERVER_IP: 203.109.103.26
          #SERVER_USER: administrator
          DEPLOY_USER: epiu
          DEPLOY_PASSWORD: "Ethics@2023"
          CONTAINER_REGISTRY: https://index.docker.io/v1/
          CONTAINER_IMAGE: epiu/gtpos-ui
          CONTAINER_TEST_IMAGE: $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG
          CONTAINER_RELEASE_IMAGE: $CONTAINER_IMAGE:dev
          CONTAINER_NAME: gtpos_ui_dev
 
 
      - if: $CI_COMMIT_REF_NAME ==  "main"
        variables:
          DOCKER_TLS_CERTDIR: ""
          #SERVER_IP: 203.109.103.26
          #SERVER_USER: administrator
          DEPLOY_USER: epiu
          DEPLOY_PASSWORD: "Ethics@2023"
          CONTAINER_REGISTRY: https://index.docker.io/v1/
          CONTAINER_IMAGE: epiu/gtpos-ui
          CONTAINER_TEST_IMAGE: $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG
          CONTAINER_RELEASE_IMAGE: $CONTAINER_IMAGE:qa
          CONTAINER_NAME: gtpos_ui_stage
          #API_URL: http://apiqa.gtpos.ethicstechnology.net
          REACT_APP_PLATFORM: "Android"
          REACT_APP_BACKEND_API_URL: "http://apiqa.gtpos.ethicstechnology.net/api/"
 
 
      - if: $CI_COMMIT_REF_NAME ==  "production"
        variables:
          DOCKER_TLS_CERTDIR: ""
          #SERVER_IP: 203.109.103.26
          #SERVER_USER: administrator
          DEPLOY_USER: epiu
          DEPLOY_PASSWORD: "Ethics@2023"
          CONTAINER_REGISTRY: https://index.docker.io/v1/
          CONTAINER_IMAGE: epiu/gtpos-ui
          CONTAINER_TEST_IMAGE: $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG
          CONTAINER_RELEASE_IMAGE: $CONTAINER_IMAGE:prod
          CONTAINER_NAME: gtpos_ui
 
 
build:
  stage: ui-build
  before_script:
    - docker login -u $DEPLOY_USER -p $DEPLOY_PASSWORD $CONTAINER_REGISTRY
  script:
    - docker build --pull --build-arg REACT_APP_BACKEND_API_URL=$REACT_APP_BACKEND_API_URL --build-arg REACT_APP_PLATFORM=$REACT_APP_PLATFORM -t $CONTAINER_TEST_IMAGE -f apps/web/Dockerfile .
  rules:
    - if: $CI_COMMIT_REF_NAME ==  "main"
 
 
release:
  stage: ui-release
  before_script:
    - docker login -u $DEPLOY_USER -p $DEPLOY_PASSWORD $CONTAINER_REGISTRY
  script:
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  rules:
    - if: $CI_COMMIT_REF_NAME ==  "main"
 
deploy:
  stage: ui-deploy
  script:
    - apk add --update curl
    - curl -XPOST $CD_URL_STAGE
  environment:
      name: stage-ui
      url: http://qa.gtpos.ethicstechnology.net/
  rules:
    - if: $CI_COMMIT_REF_NAME ==  "main"